name: '🚀 Build and Publish Release'

on:
  push:
    tags: ['v*']

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-prebuilds.yaml
    secrets: inherit
    permissions:
      contents: write
      packages: write