name: "🚀 Build and Publish Release"

on:
  push:
    tags: ["v*"]

jobs:
  build:
    uses: ./.github/workflows/build-prebuilds.yaml

  package-and-publish:
    name: "Package and Publish"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for tags

      - uses: actions/setup-node@v5
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build TypeScript
        run: npm run build:tsc

      - name: Download all prebuilds
        uses: actions/download-artifact@v5
        with:
          pattern: prebuild-*
          path: prebuilds-artifacts

      - name: Download FFmpeg binaries
        uses: actions/download-artifact@v5
        with:
          pattern: ffmpeg-v7.1.2-*
          path: ffmpeg-binaries

      - name: Prepare prebuilds structure
        run: |
          mkdir -p prebuilds

          # Copy all prebuilds to a single directory structure
          for dir in prebuilds-artifacts/*/; do
            cp -r "$dir"* prebuilds/
          done

          echo "Combined prebuilds structure:"
          ls -laR prebuilds/

          # Verify we have all expected platforms
          echo -e "\nVerifying platform coverage:"
          for platform in darwin-x64 darwin-arm64 linux-x64 linux-arm64 win32-x64-mingw win32-arm64-mingw win32-x64-msvc win32-arm64-msvc; do
            if [ -d "prebuilds/$platform" ]; then
              echo "✓ $platform"
            else
              echo "✗ $platform missing"
              exit 1
            fi
          done

      - name: Create platform packages
        run: |
          node scripts/create-platform-packages.js

          # Copy prebuilds to platform packages (already named node-av.node)
          for platform in darwin-x64 darwin-arm64 linux-x64 linux-arm64 win32-x64-mingw win32-arm64-mingw win32-x64-msvc win32-arm64-msvc; do
            if [ -d "prebuilds/$platform" ]; then
              cp "prebuilds/$platform/node-av.node" "packages/$platform/node-av.node"
              echo "Copied binary for $platform"
            fi
          done

          echo "Platform packages created:"
          ls -la packages/
          for pkg in packages/*/; do
            echo "Contents of $pkg:"
            ls -la "$pkg"
          done

      - name: Update version
        run: |
          # Extract version from tag
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "Version: $VERSION"

          # Check if main package needs version update
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            echo "Updating main package version from $CURRENT_VERSION to $VERSION"
            npm version $VERSION --no-git-tag-version
          else
            echo "Main package already at version $VERSION"
          fi

          # Update platform package versions
          for pkg in packages/*/package.json; do
            if [ -f "$pkg" ]; then
              cd $(dirname "$pkg")
              PKG_VERSION=$(node -p "require('./package.json').version")
              if [ "$PKG_VERSION" != "$VERSION" ]; then
                echo "Updating $(basename $(dirname "$pkg")) from $PKG_VERSION to $VERSION"
                npm version $VERSION --no-git-tag-version
              else
                echo "$(basename $(dirname "$pkg")) already at version $VERSION"
              fi
              cd -
            fi
          done

      - name: Create release archives
        run: |
          # Create archives for each platform (including new Windows variants)
          for platform in darwin-x64 darwin-arm64 linux-x64 linux-arm64 win32-x64-mingw win32-arm64-mingw win32-x64-msvc win32-arm64-msvc; do
            if [ -d "prebuilds/$platform" ]; then
              zip -r "node-av-${platform}-${GITHUB_REF#refs/tags/}.zip" "prebuilds/$platform"
              echo "Created: node-av-${platform}-${GITHUB_REF#refs/tags/}.zip"
            fi
          done

          # Copy FFmpeg binaries to root for release
          if [ -d "ffmpeg-binaries" ]; then
            echo "Copying FFmpeg binaries for release:"
            for ffmpeg_dir in ffmpeg-binaries/*/; do
              if [ -d "$ffmpeg_dir" ]; then
                # Extract the artifact name from directory
                artifact_name=$(basename "$ffmpeg_dir")
                echo "Processing FFmpeg artifact: $artifact_name"

                # Create zip files for each FFmpeg binary
                if [ -d "$ffmpeg_dir" ] && [ "$(ls -A "$ffmpeg_dir")" ]; then
                  cd "$ffmpeg_dir"
                  zip -r "../../${artifact_name}" *
                  cd ../..
                  echo "Created: ${artifact_name}"
                fi
              fi
            done
          fi

          echo "All release archives created:"
          ls -la *.zip

      - name: Generate release notes from CHANGELOG
        id: release_notes
        run: |
          # Extract version without 'v' prefix
          VERSION="${{ github.ref_name }}"
          VERSION_NO_V="${VERSION#v}"

          # Start building the release body
          cat > release_notes.md << 'EOF'
          ## node-av Release ${{ github.ref_name }}

          ### 📦 Updated Packages

          The following platform packages have been updated to ${{ github.ref_name }}:
          - `@seydx/node-av-darwin-arm64@${{ github.ref_name }}`
          - `@seydx/node-av-darwin-x64@${{ github.ref_name }}`
          - `@seydx/node-av-linux-arm64@${{ github.ref_name }}`
          - `@seydx/node-av-linux-x64@${{ github.ref_name }}`
          - `@seydx/node-av-win32-arm64@${{ github.ref_name }}`
          - `@seydx/node-av-win32-x64@${{ github.ref_name }}`
          EOF

          # Extract the specific version section from CHANGELOG.md
          if [ -f "CHANGELOG.md" ]; then
            # Extract content for this specific version
            VERSION_CONTENT=$(sed -n "/## \[${VERSION_NO_V}\]/,/## \[/p" CHANGELOG.md | sed '$d')

            if [ -n "$VERSION_CONTENT" ]; then
              echo "" >> release_notes.md
              # Remove the version header line and add content
              echo "$VERSION_CONTENT" | tail -n +2 >> release_notes.md
            fi
          fi

          # Always add commit history
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ github.ref_name }}^ 2>/dev/null || echo "")
          if [ -n "$PREVIOUS_TAG" ]; then
            echo "" >> release_notes.md
            echo "### 📋 All Changes since $PREVIOUS_TAG" >> release_notes.md
            echo "" >> release_notes.md
            git log --pretty=format:"- %s (%h)" $PREVIOUS_TAG..${{ github.ref_name }} >> release_notes.md
          fi

          # Output the release notes
          cat release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
          body_path: release_notes.md

      - name: Publish to NPM
        run: |
          # Publish platform packages
          for pkg_dir in packages/*/; do
            if [ -d "$pkg_dir" ]; then
              cd "$pkg_dir"
              npm publish --access public
              cd -
            fi
          done

          # Clean up artifacts that shouldn't be in the main package
          rm -rf prebuilds-artifacts
          rm -f *.zip

          # Publish main package
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
