name: "🐳 Build Docker Images"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday
  # push:
  #   branches: [main]
  #   paths:
  #     - 'externals/jellyfin-ffmpeg/**'
  #     - '.github/workflows/build-docker-images.yaml'
  #     - '.github/workflows/build-prebuilds.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-ffmpeg

jobs:
  build_docker_images:
    name: "Build ${{ matrix.target }} Docker Image"
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - target: linux64
            variant: gpl
            platform: linux/amd64
            runner: ubuntu-latest
          - target: linuxarm64
            variant: gpl
            platform: linux/arm64
            runner: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          cd externals/jellyfin-ffmpeg/builder
          # Set our repository instead of jellyfin's
          export GITHUB_REPOSITORY="${{ github.repository }}"
          ./makeimage.sh ${{ matrix.target }} ${{ matrix.variant }}

      - name: Tag and Push Image
        run: |
          # The makeimage.sh creates a local image, we need to push it
          SOURCE_IMAGE="ghcr.io/${{ github.repository }}/${{ matrix.target }}-${{ matrix.variant }}:latest"

          # Push the main image
          docker push "$SOURCE_IMAGE"

          # Create and push simplified tag
          IMAGE_TAG="${{ env.REGISTRY }}/${{ github.repository }}:${{ matrix.target }}-${{ matrix.variant }}"
          docker tag "$SOURCE_IMAGE" "$IMAGE_TAG"
          docker push "$IMAGE_TAG"

          # Create and push date tag
          DATE_TAG="${{ env.REGISTRY }}/${{ github.repository }}:${{ matrix.target }}-${{ matrix.variant }}-$(date +%Y%m%d)"
          docker tag "$SOURCE_IMAGE" "$DATE_TAG"
          docker push "$DATE_TAG"
